---
- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Execute show version on the switch and register
      aoscx_command:
        commands: ['show version']
      register: show_version_output

    - name: Output registered variable
      debug:
        var: show_version_output
